version: "3"

services:
  nextjs:
    build: ./client
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/archive/thez0ne.xyz:/etc/nginx/certs
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: postgres-db
